# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ran_messages.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'ran_messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12ran_messages.proto\x12\roran.ransm.v1\"\xa4\x01\n\x14RanParameterMapEntry\x12*\n\x03key\x18\x01 \x02(\x0e\x32\x1d.oran.ransm.v1.RanParameterId\x12\x15\n\x0bint64_value\x18\x02 \x01(\x03H\x00\x12\x16\n\x0cstring_value\x18\x03 \x01(\tH\x00\x12(\n\x07ue_list\x18\x04 \x01(\x0b\x32\x15.oran.ransm.v1.UeListH\x00\x42\x07\n\x05value\"L\n\x14RanIndicationRequest\x12\x34\n\rtarget_params\x18\x01 \x03(\x0e\x32\x1d.oran.ransm.v1.RanParameterId\"O\n\x15RanIndicationResponse\x12\x36\n\tparam_map\x18\x01 \x03(\x0b\x32#.oran.ransm.v1.RanParameterMapEntry\"R\n\x11RanControlRequest\x12=\n\x10target_param_map\x18\x01 \x03(\x0b\x32#.oran.ransm.v1.RanParameterMapEntry\"\x8d\x02\n\nRanMessage\x12/\n\x08msg_type\x18\x01 \x02(\x0e\x32\x1d.oran.ransm.v1.RanMessageType\x12\x41\n\x12indication_request\x18\x02 \x01(\x0b\x32#.oran.ransm.v1.RanIndicationRequestH\x00\x12\x43\n\x13indication_response\x18\x03 \x01(\x0b\x32$.oran.ransm.v1.RanIndicationResponseH\x00\x12;\n\x0f\x63ontrol_request\x18\x04 \x01(\x0b\x32 .oran.ransm.v1.RanControlRequestH\x00\x42\t\n\x07payload\"\x93\x01\n\x06UeInfo\x12\x0c\n\x04rnti\x18\x01 \x02(\r\x12\x10\n\x08rsrp_dbm\x18\x02 \x01(\x02\x12\x0e\n\x06\x62\x65r_ul\x18\x03 \x01(\x02\x12\x0e\n\x06\x62\x65r_dl\x18\x04 \x01(\x02\x12\x0e\n\x06mcs_ul\x18\x05 \x01(\r\x12\x0e\n\x06mcs_dl\x18\x06 \x01(\r\x12\x10\n\x08\x61ux_flag\x18\x08 \x01(\x08\x12\x11\n\taux_value\x18\t \x01(\x02J\x04\x08\x07\x10\x08\"G\n\x06UeList\x12\x15\n\rconnected_ues\x18\x01 \x02(\r\x12&\n\x07ue_info\x18\x02 \x03(\x0b\x32\x15.oran.ransm.v1.UeInfo*`\n\x0eRanMessageType\x12\x10\n\x0cSUBSCRIPTION\x10\x01\x12\x16\n\x12INDICATION_REQUEST\x10\x02\x12\x17\n\x13INDICATION_RESPONSE\x10\x03\x12\x0b\n\x07\x43ONTROL\x10\x04*X\n\x0eRanParameterId\x12\n\n\x06GNB_ID\x10\x01\x12\x0b\n\x07UE_LIST\x10\x03\x12\x14\n\x10GLOBAL_PRB_ALLOC\x10\x05\x12\x0b\n\x07MAX_PRB\x10\x06\"\x04\x08\x02\x10\x02\"\x04\x08\x04\x10\x04')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ran_messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RANMESSAGETYPE']._serialized_start=942
  _globals['_RANMESSAGETYPE']._serialized_end=1038
  _globals['_RANPARAMETERID']._serialized_start=1040
  _globals['_RANPARAMETERID']._serialized_end=1128
  _globals['_RANPARAMETERMAPENTRY']._serialized_start=38
  _globals['_RANPARAMETERMAPENTRY']._serialized_end=202
  _globals['_RANINDICATIONREQUEST']._serialized_start=204
  _globals['_RANINDICATIONREQUEST']._serialized_end=280
  _globals['_RANINDICATIONRESPONSE']._serialized_start=282
  _globals['_RANINDICATIONRESPONSE']._serialized_end=361
  _globals['_RANCONTROLREQUEST']._serialized_start=363
  _globals['_RANCONTROLREQUEST']._serialized_end=445
  _globals['_RANMESSAGE']._serialized_start=448
  _globals['_RANMESSAGE']._serialized_end=717
  _globals['_UEINFO']._serialized_start=720
  _globals['_UEINFO']._serialized_end=867
  _globals['_UELIST']._serialized_start=869
  _globals['_UELIST']._serialized_end=940
# @@protoc_insertion_point(module_scope)
